[build]
  # Build command
  command = "yarn build"
  # Build output directory
  publish = "dist"
  # Source code directory
  base = "client"

[[redirects]]
  # Redirect all routes to index.html for Single Page Applications (SPA)
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  # Set Node.js version to 16.20.2
  NODE_VERSION = "16.20.2"

## (optional) Settings for Netlify Dev
## https://github.com/netlify/cli/blob/master/docs/netlify-dev.md#project-detection
#[dev]
#  command = "yarn start" # Command to start your dev server
#  port = 3000 # Port that the dev server will be listening on
#  publish = "dist" # Folder with the static content for _redirect file

## more info on configuring this file: https://www.netlify.com/docs/netlify-toml-reference/